import { chapters } from './content.js';
const $=s=>document.querySelector(s), reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let target=0,current=0,active=-1,paused=reduced,orbit=false,explode=false,renderer=null,lastTime=0,swapTimer,scanTimer,audioCtx,audioGain,soundOn=false,dragStart=null,dragging=false,dragRotation=0;
const initial=chapters.findIndex(c=>c.id===location.hash.slice(1));if(initial>=0)target=current=initial;
const nav=$('#chapterNav'),indexLinks=$('#indexLinks');
chapters.forEach((c,i)=>{nav.insertAdjacentHTML('beforeend',`<button data-go="${i}" data-label="${c.name}" aria-label="${c.name}" aria-current="false">0${i}</button>`);indexLinks.insertAdjacentHTML('beforeend',`<button data-go="${i}"><span>0${i}</span>${c.name}<i>↗</i></button>`)});
function setPaused(value){paused=value;document.body.classList.toggle('paused',paused);$('#motion').setAttribute('aria-pressed',String(paused));$('#motion').setAttribute('aria-label',paused?'Resume animation':'Pause animation');$('#motion').textContent=paused?'▷':'Ⅱ'}
setPaused(paused);if(reduced)document.body.classList.add('reduced');
function setOrbit(value){orbit=value;document.body.classList.toggle('orbiting',value);$('#orbit').setAttribute('aria-pressed',String(value));$('#orbit').textContent=value?'↔ Return to journey':'↔ Rotate object';$('#world').style.cursor=value?'grab':'';$('#sceneNotice').textContent=value?'Drag to rotate. Scroll to return to the journey.':''}
function go(i){renderer?.cancelRoom();target=Math.max(0,Math.min(7,i));if(reduced)current=target;setOrbit(false);document.querySelectorAll('dialog[open]').forEach(d=>d.close());if(soundOn)chime(i);history.replaceState(null,'','#'+chapters[Math.round(target)].id)}
function updateStory(i,immediate=false){active=i;const c=chapters[i];history.replaceState(null,'','#'+c.id);clearTimeout(swapTimer);$('#story').classList.add('changing');const apply=()=>{$('#eyebrow').textContent=c.eyebrow;$('#headline').innerHTML=c.title;$('#intro').innerHTML=c.intro;$('#ctaText').textContent=i===0?'Walk into the studio':'Enter '+c.name;$('#storyFoot').textContent=c.foot;$('#chapterNumber').textContent=`0${i} — ${c.name.toUpperCase()}`;$('#objectLabel').textContent=`0${i+1} / ${c.object}`;$('#objectSub').textContent=c.sub;document.documentElement.style.setProperty('--accent',c.color);nav.querySelectorAll('button').forEach((b,n)=>b.setAttribute('aria-current',String(n===i)));$('#story').classList.remove('changing');$('#journeyHint').innerHTML=i===7?'BACK TO THE BEGINNING<small>scroll up or press Home</small>':'SCROLL TO DISCOVER<small>or use ↑ ↓</small>'};if(immediate||reduced)apply();else swapTimer=setTimeout(apply,140)}
updateStory(Math.round(current),true);
function showDetails(){const c=chapters[active];$('#detailEyebrow').textContent=c.eyebrow;$('#detailBody').innerHTML=c.body;$('#detailDialog').showModal();$('#detailDialog').scrollTop=0;const scan=$('#scanButton');if(scan)scan.onclick=runScan}
$('#detailsOpen').onclick=()=>{if(!renderer||renderer.inRoom)showDetails();else if(active===0)go(1);else renderer.enterRoom(active)};$('#exitRoom').onclick=()=>renderer?.leaveRoom();$('#indexOpen').onclick=()=>$('#indexDialog').showModal();
document.addEventListener('click',e=>{const close=e.target.closest('[data-close]');if(close)close.closest('dialog').close();const jump=e.target.closest('[data-go]');if(jump)go(Number(jump.dataset.go))});
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});d.addEventListener('close',()=>clearInterval(scanTimer))});
function runScan(){clearInterval(scanTimer);const btn=$('#scanButton');btn.disabled=true;btn.textContent='Reading sample…';let p=0;scanTimer=setInterval(()=>{p=Math.min(100,p+5);const bar=$('#scanProgress');if(!bar){clearInterval(scanTimer);return}bar.style.width=p+'%';if(p===100){clearInterval(scanTimer);btn.disabled=false;btn.innerHTML='Replay demo <span>↗</span>';$('#scanResults').innerHTML='<div class="pulse-results"><div><span>IDENTITY / REVIEW</span>Review privileged access assignments.</div><div><span class="warn">MAIL / PRIORITY</span>Check protection policy coverage.</div><div><span>ENDPOINTS / REVIEW</span>Confirm device compliance policies.</div><div><span>HANDOVER / NEXT</span>Prioritise findings and plan the fixes.</div></div><p class="note">Sample findings for illustration. This is not a live audit or an assessment of your tenant.</p>'}},reduced?1:65)}
$('#motion').onclick=()=>setPaused(!paused);$('#orbit').onclick=()=>setOrbit(!orbit);$('#explode').onclick=()=>{explode=!explode;$('#explode').setAttribute('aria-pressed',String(explode));$('#explode').textContent=explode?'⊹ Reassemble':'⊹ Disassemble';if(soundOn)chime(explode?4:1)};
function chime(i){if(!audioCtx||audioCtx.state!=='running')return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=220*Math.pow(2,i/12);g.gain.setValueAtTime(0,audioCtx.currentTime);g.gain.linearRampToValueAtTime(.045,audioCtx.currentTime+.03);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+1.4);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+1.5)}
$('#sound').onclick=async()=>{try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioGain=audioCtx.createGain();audioGain.gain.value=0;audioGain.connect(audioCtx.destination);[55,82.4069,110.12].forEach((f,i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=f;g.gain.value=i===0?.25:.09;o.connect(g);g.connect(audioGain);o.start()})}await audioCtx.resume();soundOn=!soundOn;audioGain.gain.setTargetAtTime(soundOn?.12:0,audioCtx.currentTime,.5);$('#sound').setAttribute('aria-pressed',String(soundOn));$('#sound').setAttribute('aria-label',soundOn?'Disable ambient sound':'Enable ambient sound');$('#soundState').textContent=soundOn?'ON':'OFF';if(soundOn)chime(active)}catch{$('#soundState').textContent='N/A';$('#sound').disabled=true}};
function modalOpen(){return !!document.querySelector('dialog[open]')}
addEventListener('wheel',e=>{if(modalOpen())return;e.preventDefault();if(renderer?.inRoom)return;if(orbit)setOrbit(false);const d=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?innerHeight:1);target=Math.max(0,Math.min(7,target+Math.max(-150,Math.min(150,d))*.0018));if(reduced)current=target},{passive:false});
addEventListener('keydown',e=>{if(modalOpen())return;const tag=e.target.tagName;if(['INPUT','TEXTAREA','SELECT'].includes(tag))return;if((e.key==='ArrowDown'||e.key==='PageDown')&&!renderer?.inRoom){e.preventDefault();go(Math.floor(target+.1)+1)}if((e.key==='ArrowUp'||e.key==='PageUp')&&!renderer?.inRoom){e.preventDefault();go(Math.ceil(target-.1)-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(7)}if(e.key==='Escape'){if(renderer?.inRoom)renderer.leaveRoom();setOrbit(false)}});
addEventListener('hashchange',()=>{const i=chapters.findIndex(c=>c.id===location.hash.slice(1));if(i>=0)go(i)});
const canvas=$('#world');canvas.addEventListener('pointerdown',e=>{dragStart={x:e.clientX,y:e.clientY,lastY:e.clientY,lastX:e.clientX};dragging=false;canvas.setPointerCapture(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(renderer)renderer.pointer(e.clientX/innerWidth*2-1,e.clientY/innerHeight*2-1);if(!dragStart)return;if(Math.hypot(e.clientX-dragStart.x,e.clientY-dragStart.y)>6)dragging=true;if(orbit){dragRotation+=(e.clientX-dragStart.lastX)*.009;canvas.style.cursor='grabbing'}else if(e.pointerType!=='mouse'&&!renderer?.inRoom){target=Math.max(0,Math.min(7,target+(dragStart.lastY-e.clientY)*.004));if(reduced)current=target}dragStart.lastY=e.clientY;dragStart.lastX=e.clientX});
canvas.addEventListener('pointerup',e=>{if(dragStart&&!dragging&&!orbit){const action=renderer?.hit(e.clientX,e.clientY);if(action){if(action.kind==='enter'){target=action.index;updateStory(action.index,true);renderer.enterRoom(action.index)}else{updateStory(action.index,true);showDetails()}}}dragStart=null;if(orbit)canvas.style.cursor='grab'});canvas.addEventListener('pointercancel',()=>dragStart=null);
addEventListener('resize',()=>renderer?.resize());
let clock=0;function frame(t){requestAnimationFrame(frame);const dt=Math.min(.05,(t-lastTime)/1000||.016);lastTime=t;if(document.hidden)return;current+=(target-current)*(reduced?1:1-Math.exp(-dt*5));if(Math.abs(target-current)<.0002)current=target;const index=renderer?.inRoom?renderer.roomIndex:Math.round(current);if(index!==active)updateStory(index);document.body.classList.toggle('inside-room',!!renderer?.inRoom);$('#exitRoom').hidden=!renderer?.inRoom;$('#ctaText').textContent=renderer?.inRoom?'Explore this room':active===0?'Walk into the studio':'Enter '+chapters[active].name;$('#journeyHint').innerHTML=renderer?.inRoom?'MOVE THE MOUSE TO LOOK AROUND<small>Esc to return to the hall</small>':'SCROLL TO WALK<small>click a door to enter · ↑ ↓</small>';$('#progress').style.width=(current/7*100)+'%';if(!paused&&!modalOpen())clock+=dt;renderer?.update({current,clock,dt,paused:paused||modalOpen(),explode,orbit,dragRotation});}requestAnimationFrame(frame);
const fail=()=>{document.body.classList.add('fallback');$('#sceneNotice').textContent='The 3D view is unavailable here. All chapters and information remain accessible.'};
import('./scene.js').then(m=>{try{renderer=m.createScene(canvas,chapters);$('#sceneNotice').textContent=''}catch(e){console.error('3D initialization:',e);fail()}}).catch(e=>{console.error('3D loading:',e);fail()});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();renderer=null;fail()});
